# fly.toml app configuration file generated for y-webrtc on 2023-10-21T19:18:20-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "y-webrtc"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
